# MCA Algorithm Implemantaion

In [16]:
import numpy as np  # linear algebra

In [17]:
a = np.random.rand(3, 3)

print(a)

[[0.09315298 0.5775177  0.23752834]
 [0.49732565 0.23946155 0.87793212]
 [0.35654195 0.38788844 0.00396908]]


In [18]:
def minors_matrix_det(matrix, m, i, j):
    return np.linalg.det(np.delete(np.delete(matrix, i, axis=0), j, axis=1))

In [19]:
a_inverse_test = np.linalg.inv(a)

a_minors = np.zeros((3, 3))
h = np.zeros((3, 3))


for i in range(3):
    for j in range(3):
        h[i, j] = pow(-1, (i + j))
        a_minors[i, j] = minors_matrix_det(a, 3, i, j)

a_cofactor = a_minors * h

a_determinant = np.linalg.det(a)

a_adjoint = a_cofactor.T

a_inverse = a_adjoint / a_determinant

print(a_inverse)
print(a_inverse_test)


[[-1.95681572  0.51769828  2.59385632]
 [ 1.79233902 -0.48587196  0.20944202]
 [ 0.61961323  0.97830231 -1.52647859]]
[[-1.95681572  0.51769828  2.59385632]
 [ 1.79233902 -0.48587196  0.20944202]
 [ 0.61961323  0.97830231 -1.52647859]]
